import Styles from '@/styles/TheVillage.module.css';
import Image from 'next/image';
import Village from "../../../public/survival.jpg"
import Head from 'next/head'
const SurvivingTogether = () => {
  return (
    <>
      <Head>
        <title>Surviving Together</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={Styles.name}>
        <h1>Surviving Together</h1></div>

      <div className={Styles.p}>
        <h3>Estimated reading time: 19 mins 28 sec</h3>
        <div className={Styles.image}>
          <Image src={Village} alt="Village" width={900} height={500} priority />
        </div>
        <p>
          “It was the era of apocalypse. Due to war, around 90 percent of the human population became extinct, left behind only a small group of survivors in a desolate wasteland. Around the world, there were many groups of survivors traveled from place to place in search of food and shelter. Jona was part of one of these groups and was the only survivor from his family."
          <br /><br />
          "Just like him, many people in his group had also lost their family members, ranging from young to old age. When Jona and others heard about the shelter in the destroyed city, which was situated to the north. They started their journey, with around 30 people in the group. But as the time passed, the number declined. Some suffered from diseases, some died of hunger, and some couldn't bear the trauma of the war.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Listen everyone, gather together, we are about to leave now.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Ron:</span> Hey Jona, do you think how long will it take us to make to the city?
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Ron, this is the 10th time you have asked me the same question. Just don't worry about it, we will make it in time. You better look after your mom and go back to her.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Ron:</span>  Alright then.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Ron never gets tired of asking the same question to you, does he?
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Yes, that's what burdens me more. His mother situation is getting worse day by day. And I couldn't even help her but just give them hope that she might get treated at the shelter, where we don't know the exact location.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> At least we know that it's in the north direction. You're the only one who can hold this group together. So you have no right to be pessimistic. As long as we stay focused and keep traveling in the right direction, we will all be fine.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> One thing you're stating right is that worrying won't help us. We have to look for the shelter as soon as possible, and we can't afford to lose more people.
          <br /><br />
          “Jona's group started their journey, and because they solely relied on the north direction, they ended up at the opening of the jungle.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> This is going to be challenging. Mark, make sure everyone is well-prepared. We might confront any wild animals, so make anything useful for others to use as a weapon for protecting themselves as well as others.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> On it. Weapon is ready. A handmade spear for everyone. Take one spear each.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Ron:</span>  Where is my weapon Mark ?
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Sorry kid. You can't carry a spear.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Ron:</span>  Who are you calling a kid? I'm 12 years old.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> 12 year old is still the definition of a kid. So quit asking for a spear.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Just make something smaller for him, Mark. You always act like a kid with him.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Fine, fine. Here, take this, you kid.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Ron:</span>  You better watch your tone, old hag.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Who are you calling old hag now?
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> I said enough.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Who want more spears, don't forget to witness the crafting talent of mark the great.
          <br /><br />
          “They entered the jungle domain with all the preparation. In the jungle, They saw two Asian monk kids. They were in bad shape, from their clothing to physical state, but despite all of that, they had a soft smile on their face.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Are you guys ok? Need anything to eat?
          Asian kid monk: Thank you, but we can't accept it. There are others who need it more than us. We've been living in the jungle for a while now. It is our time to travel to the mountains.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> You should both come with us. There is a shelter in the city where we can get food and other resources. You could come with us and rest there for a while.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Asian monk kid:</span> We are grateful for your offer, but we have a destination in mind. Our goal is to reach a mountain monastery where we can continue our spiritual practice.
          <br /><br />
          “As the two Asian monk kids walked away with a smile on their faces, they left everyone with questions about their mysterious presence in the jungle.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> What just happened? How can anyone still believe in this kind of stuff even after the apocalypse.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Maybe they have a good reason to travel to the mountain. Everyone has the right to choose their own path. But right now we need to keep moving forward. We can't afford to waste any more time.
          <br /><br />
          “After walking for hours in the heat, Jona noticed that everyone was tired and decided to take a short break.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Let's take a quick break to rest and replenish our energy. Mark and I will stand guard and keep an eye on any wild animals.
          <br /><br />
          “Suddenly they heard a baby cry. In order to find out, Jona and others followed the voice. They came across a hole and found a woman inside, with the baby tied to her. They took her out of the hole, but she was still unconscious. Jona carefully untied the child from the mother and tried to calm down the baby. They tried to wake her up, but she remained unconscious. After long hours, she gained consciousness. But there was a terror in her eyes. She asked Jona about the baby. A girl from the group came and gave her back the baby.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> What exactly happened? How did you end in this deep jungle with the baby?
          <span className={Styles.characterName}> ⫸ Misa:</span> For right now, all you need to know is my name. We need to leave this place right now and find ourselves a safer place on the mountain.
          <br /><br />
          “Jona agreed, and by evening they reached the top of the mountain. After everything was settled, the group sat around the bonfire, and Misa started talking.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> I was at a shelter near the dam with many other people when, one night, a group of human-like figures suddenly attacked, killing everyone they saw. At first, I thought they were just raiders looking for food, but they were actually eating human flesh. I watched everything through a hole in the door. Their eyes, skin, nails, and teeth were unlike anything human but more like that of some kind of creature. I would say they were half-human and half-creature.
          <br /><br />
          My baby started to cry, which caught their attention, and they started banging on the door. Somehow I managed to escape through the back window and stayed at the bottom of the dam all night. The next morning, I decided to head back to the shelter. What I saw there is impossible to forget. The place was full of dead bodies, many of which had been half-eaten. Some were missing their heads, legs, or arms.
          <br /><br />
          I didn't know what to do, then there was this guy from the watchtower who asked me for help. He had been injured by those creatures. After we got on the tower, the man had been cutting up one of the creature's body. When I asked, He called himself a doctor and was trying to find out more about the creatures. At that time, the sun was rising slowly, and as sunlight hit the creature's body, its skin started melting and releasing smoke at the same time. We were both shocked to see that.
          <br /><br />
          The doctor came to the conclusion that it might have been caused by a nuclear attack, leading to a mutation in the creature's body or the result of a failed military human experiment. When I asked him to show his injury, he refused it. Later on, he became just like those creatures. Luckily, I was able to escape from him. I kept running all night and then fell down in a hole. When I gained back my consciousness, I found myself among you people.
          <br /><br />
          “When Misa finished her talk, the whole atmosphere went to pin drop silence. Everyone started to looked at each other. They were able to see the fear on each other's face. To calm them down, Jona try to comfort all of them.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Everyone has their spear, right? From now on, we have to follow new rules. No one will separate from the group. We will stay close to each other, especially at night. As Misa told us, those creatures only come out at night, and they can't survive in the daylight. So we don't need to worry about it.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Now the war wasn't enough, we have to face zombies as well. We shouldn't have chosen the jungle route in the first place. This is bad. I must have done something wrong in my past life to deserve something like this.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Hold yourself together and lower your voice, Mark, or those creatures might hear us and you're scaring the other people. Being part of the group means we have to look out for each other.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Forgive me Jona, I just got carried away. It's just hard to take all at once.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Misa, can you take us to that shelter camp? We are short on food supplies.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> if we start walking in daylight, it might take 3 to 4 hours to get there. I'm familiar with this jungle, so it won't be a problem to find out the shelter.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Ron:</span>  Are we all going to die, Jona? I’m scared.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Don't say that, Ron. No one is going to die. We will get to the shelter without any harm, and didn't you say you are not a kid? You have to be brave to protect your loved ones.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Ron:</span>  I will be brave, Jona to protect my mother and others.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Little man is fire up here, someone call the firefighter, or he might set up the whole jungle on fire. Ron, you remind me of myself when I was your age. Keep that spirit up and you'll go far in life.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Mark, don't start again with Ron. Everyone, our talk is done now make sure to take enough rest. Tomorrow is an important day, and we won't be taking a break until we get to the Misa’s shelter, because of those creatures.
          <br /><br />
          “Mark’s little humor made the situation a bit calm and everyone slept soundly. The next morning, they got up and began their journey to the shelter. Jona was at the front with Misa leading them, and Mark was at the back of the group. After walking for hours without any break, they reached the shelter gate by the afternoon.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Mark, you stay outside with others. Misa and I will go inside to find the food.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> First, we need to find the mask in the medical supplies room. The smell of dead is too strong. It is hard to bear. We might find the medicines as well.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> It was a good call to leave your baby behind with others. This smell is killing me. We need to pack up all the necessary medicines as soon as possible, and then we can look for food. You should be careful around the bodies. There's a higher chance of getting infected.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> I will take care of food, and you keep looking for the medicines.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Make sure you're quick, Misa. We need to get out of here before sundown.
          <br /><br />
          “Jona continued searching through the shelves, trying to find any medicine that could be useful to them. As he searched, he couldn't help but feel uneasy about being in a room full of dead bodies."
          <br /><br />
          "On the other end, Misa made her way to the food storage room, her stomach grumbling with hunger. As she entered the room, immediately began searching for any food items. She carefully checked each shelf, looking for any canned or dried food that might have survived. After a few minutes, she found some canned vegetables and fruit. She wiped the dust off the cans and placed them in her bag."
          <br /><br />
          "A large bag of rice in the corner caught her eye. She was relieved to find it. As Misa reached for the bag of rice, she heard a scratching sound coming from one of the shelves."
          <br /><br />
          "The sound got louder, and she found out that it was coming from a bag of flour. She opened the bag and discovered a squirrel inside, barely alive. Feeling sorry for the little animal, Misa took it out and fed it some food before leaving for the medical supply room.
          When Misa got inside the medical supply room, Jona had finished packing all the medicine.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> Jona, we need to leave this palace now. The sun is about to set down.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> I'm finished packing all the medicines supplies. Have you found anything?
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> Yes, I did, some can food and big bag of rice.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> That's great, let's get back to the group now.
          <br /><br />
          “The sun was going down, and the sky had turned orange. Mark was worried they wouldn't make it to any safe place before it got dark. But then, he saw Jona and Misa coming with heavy bags, and he felt relieved because they found what they were looking for.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> It's about to get dark, and it's their time to come out and hunt. There is an engine room over the dam. It will be much safer there than this place.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Since you guys did your job, we all thought it might be a good idea to collect some wood for a fire. So we did.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> That was a good call, Mark. It's going to be a cold night, and a fire would help keep us warm. You'll be a good leader one day.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> As long as you are alive, that won't be happening.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> What did you say?
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Nothing. Just mumbling. Everyone follow Misa’s lead.
          <br /><br />
          “They arrived at the engine room and locked all the doors. Jona warned everyone to stay quiet. After eating, they spoke softly to each other.
          Suddenly, they heard a loud noise from outside the door, and they all became alert. Jona stood up and made a hand gesture for the others to stay put. He then walked over to the door and pressed his ear against it, trying to listen for any sounds from outside. With another bang outside, Misa’s baby started to cry, and Jona sensed those creatures running all around the engine room.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Calm your baby down, Misa.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> I'm trying, but she's scared.
          <br /><br />
          “Jona turned back to the group with a tense expression.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Listen, everyone, those creatures are still walking around. It's going to be a long night. We're going to stay here until morning, and then we'll try to make our way out.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> What about those creatures outside? How do we know they won't get in here?
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> The doors are strong enough. We'll be safe in here for the night.
          <br /><br />
          “Misa felt relieved, and she hugged her baby close to her chest.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> Thank goodness, I'm so scared.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> We all are scared, But we have to stay strong.
          <br /><br />
          “The group settled in for the night, trying to stay warm and calm. Misa's baby eventually fell asleep, and the others took turns keeping watch at the door. As Jona saw the morning light, he opened the door with caution. He gazed everywhere but found no one.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> It’s morning, everyone, time to get out of this place.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Look Jona footprints everywhere. How many were here last night? Any guess?
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> By on the sounds we heard last night, I'd say eight to nine creatures.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> I agree with Jona. It's important that we move far away from this place. The farther we go, the safer we'll be.
          <br /><br />
          “Misa’s baby made a sound”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> See Misa even your baby is thinking the same of you.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Alright, Mark, let's distribute some food for breakfast and move out. We can eat while walking, with you watching our back from rear.
          <br /><br />

          "Jona and his group continued their journey, traveling deeper into the jungle, and faced many obstacles along the way. They tried to avoid encountering any creatures or wild animals. Although they were running low on supplies, they had to keep going. After several days of relentless walking, they finally reached the end of the jungle."
          <br /><br />
          “The scenery ahead of them was devastated. A pile of human bones, destroyed buildings, nature had begun to take over, with trees and vines growing through the cracks of buildings, and hanging dead bodies on the bridges. The unbearable smell and birds tearing off the flesh of the corpses. They couldn't have imagined it would be like this, but the informer who had told Jona about the shelter never said anything like this.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> No, it shouldn't be like this. We traveled all this way to see this. It just can't be.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Mark, we don't know who really caused it, and we haven't even been inside the city yet. Although we are close to our final destination. We still need to stay alert. There might be other people inside the city. We have to be vigilant and careful not to put ourselves in danger.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> I agree, Jona. I would rather move forward than walking back into the jungle, which is full of creatures.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> I understand, but we can't take any unnecessary risks. We need to make sure we're fully prepared before we go any further. Let's gather supplies first. We have been travelling for days and short on supplies.
          <br /><br />
          Searching the food for the rest of the group is the first thing we should work on. Misa you will be handling the rest of the group, while Mark
          and I will be out searching for food in the city. That building over there looks fine to stay. We have no idea whether those creatures are here or not, so do not let your guard down.
          Alright, Mark. I'm going to the west of the city, and you have to search in the east.
          <br /><br />
          “As Mark started to leave, Jona shows concern.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Mark, I want you to get back to us safe.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> I will be fine. You be careful out there as well.
          <br /><br />
          “With the sense of concern to each other, they depart in the search for food. While everyone watched, both of them disappear in the city ruins. Misa, then, lead the group to a partially damaged building. Jona passed by several abandoned restaurants and supermarkets, but they had all been picked clean. The only things left were broken bottles and scattered trash. He tried to keep his spirits up, reminding himself that Mark might have better luck on the other side of the city.”
          <br /><br />
          “Jona passed by many abandoned restaurants and supermarkets, but they had all been picked clean. The only things left were broken bottles and scattered trash. He tried to keep his spirits up, reminding himself that Mark might have better luck on the other side of the city.”
          <br /><br />
          “Meanwhile, Mark was having his own struggles. The city was mostly deserted, with only the occasional abandoned houses to be seen. He was starting to worry that he wouldn't find anything when he heard a faint rustling sound coming from behind a nearby building.”
          <br /><br />
          “He made his way towards the sound, with knife in his hand. As he rounded the corner, he saw a small group of people sat around a fire, roasting rats. He approached the group, trying to keep his voice calm."
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Hey there. I'm just passing through. Mind if I join you?
          <br /><br />
          “The group gave him a suspicious glance, but eventually one of them nodded and gestured towards the fire. Mark sat down with them and watched as they ate in silence. Mark asked them about the city and shelter, but no one responded. After finishing their meal, the group split, leaving Mark alone. He stood up and brushed off his pants.”
          <br /><br />
          “As he started to walk back towards the meeting point, he noticed something bright in the distance at the top of the ruined building. Mark climbed up to investigate and found a locked suitcase. He used his knife to open it and saw that it contained several packets of sealed relief food. Mark looked around to make sure no one was watching, then took the suitcase and headed back to the meeting point without being seen by anyone.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Isn't it my lucky day? Everyone is going to be happy now. Mark, you are the best.
          <br /><br />

          “Misa, Jona and all were both there, looking worried As they felt relieved when they saw Mark.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> Thank god, you're back. We were starting to worry.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Nothing bad could happen to me. See what I have found.
          <br /><br />
          “Mark smiled and opened his backpack, revealed the supplies he had found. Jona jumped on him to express his gratitude.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Hey, calm down. I’m already exhausted by the bag carrying all this way, now you're jumping on me, might be the death of me!
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> It won't happen that easily in my watch.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Haha, I trust you, Jona. You always have my back.
          <br /><br />
          “Mark was pleased to see the happiness on their faces. He had managed to provide for the group, even if it was just for a little while. Mark told Jona about the people he had met in the city, and their unpredictable behavior.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> We should avoid contact with them, since we have supplies with us right now.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Yes, it's better to be cautious, We don't know what their intentions are or how they might react to us. Let's stick to ourselves for now and avoid any unnecessary risks.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> Knowing their state, it's certain that the shelter we have been looking for is not here anymore, or they just moved out to somewhere else.
          What do you think of it, Jona?
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> At this point, I'm not even sure, but one thing I'm sure is we need to keep moving ahead to the north.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Then we must leave this place in the dark. It will be safer than going out in a daylight.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> What about the creatures? They exist here as well. We can't take that much risk.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> We can stay here for a night, to see if there are any creatures or not, lurking around the city. Having a good number of buildings around us will work in our favor. We'll be able to cover a large area and keep watch from different vantage points.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> It will be all dark, how are we going to do watch.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Don't you worry about that. We will require only ears, not eyes. Back then, we separated from each other to look out for food. I had collected empty bottles, cans, and strings. We can make good use of them by putting small rocks in them and tying string with cans and bottles. We will spread them all over the area, so if anyone comes at night, we will know it. I'm sure that, no one will wander around all these debris in pitch dark except those creatures.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> That's really smart thinking, Jona. I wouldn't have thought of that myself. It just shows that two heads are better than one.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Let begin our work then before it gets dark.
          <br /><br />
          “Everyone started to work according to Jona’s plan and spread the string of cans and bottles all around the area. After that, they moved to their positions on top of the building. Every capable individual was on watch, but they didn't hear a single movement on the ground. It was a good sign for them to travel at night and go further ahead in the city. The following morning, they gathered to discuss their departure plan.”
          <br /><br />

          <span className={Styles.characterName}> ⫸ Jona:</span> Alright, everyone, it looks like our plan worked perfectly. There wasn't a single sound to be heard last night. That means it's safe for us to continue on our journey tonight. One more thing, since it'll be pitch dark out there, we'll need some help to navigate. I suggest we use some fire to light our way. I know it's risky, but it's the best way for us to make our way through the city without getting lost.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> Jona, you forgot to mention Mark, he has been working hard to set up our route through the city. So, this time he'll lead us through the way.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Yes, this time the lead is in his hand. Since he is familiar with the route we will be taking.
          <br /><br />
          “As they move through the city under the cover of darkness with the firelight, the quietness of the city was unsettling for all of them. The path Mark had marked led them to a giant hole. It was caused by the bomb. They approached the massive hole cautiously and walked around it, keeping a safe distance. But then, Mark suddenly stopped.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Jona, I marked the path only until this point. I’m not familiar with what await us ahead.
          <br /><br />
          “Despite being in an unfamiliar place, Mark and Jona agreed to keep moving forward with the group. Soon, they came across a building with a fire burning outside. Mark signaled for Jona to stay back while he went to investigate.”
          <br /><br />
          After a quick look around, Mark returned to Jona with heavy breath and whispered.
          <br /><br />
          Mark: It's not safe. There are people inside, and they're armed. We need to be careful. It would be better if we change the path and took a longer way to bypass the building.
          <br /><br />
          “Jona agreed with Mark, and the group decided to take a longer route to avoid the building with the armed men. They knew it would take more time, but they preferred to be safe than sorry. But this time luck wasn't with them."
          <br /><br />
          "Someone fired a buttlet at them. It was hard to find where did it came from. Jona put out all the firelight and hid behind the wall. Mark and Jona quickly realized that the shooter was on top of the building with a little torch light.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> I'll distract the shooter with fire by running the other way. You take everyone out of here quietly without any fire.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> That's crazy! I'm not leaving you alone with a shooter
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> We don't have any better ideas, Jona. Trust me, I can handle it. You need to keep everyone else safe.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Promise me you'll meet me at the rendezvous point.
          <br /><br />

          “They hugged quickly, then went their separate ways. Just in seconds, Jona heard 2 more shots.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Mark, you idiot, always wanting to be the hero. Please come back safely.
          <br /><br />
          “Jona and the group got out of the reach of the shooter and kept running until morning light. They were out of the city area. Jona waited for Mark to come, but hours went by, and he didn't come."
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> We need to leave now. He is not coming. It’s been hours.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Misa, but I can't just leave without Mark. He's my friend, and I can't abandon him like this.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> I understand that, Jona, but we have to think about our own safety too. We don't know what happened to Mark, and it's not safe to stay here any longer. We need to leave now.
          <br /><br />
          “Jona thought about it for a moment, weighing his options. He knew Misa was right, but he couldn't shake off the feeling of leaving his friend behind.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Let's leave now. But I'll come back and look for him once I safely deliver all the people to the shelter.
          <br /><br />
          “Jona stood up with determination and led the group. He took them along the road route. Along the way, the group expanded as others joined with the hope of finding refuge in the shelter.”
          <br /><br />
          “The absence of mark made Jona fearless. He faced all the obstacles without any fear. Despite encountering creatures, Jona refused to back down and fought his way through with the help of the people in his group. They were no longer hiding. He had created a fighter's aura among the group, with everyone, from kids to the elderly, each carrying at least three kinds of weapons.”
          <br /><br />
          “From a distance, Misa saw something.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> Jona, look! There are some red flags behind the walls.
          <br /><br />
          “When Jona looked at it. He burst in tears and got down on knees.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> Jona what happened, are you ok.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Misa we have finally found the shelter we have been looking for all this time.
          <br /><br />
          “All the people started to run toward the shelter with happiness on their faces. Misa lifted Jona from the ground and walked together to the shelter.”
          <br /><br />
          “Misa freed her emotions with him as well.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> Jona, we did it. It was possible all because of you and mark. You were the only two who held back this group and led us this far. You gave me and my baby new life, Jona. We would be dead if you hadn't shown up there.
          <br /><br />
          “They were all welcomed by the shelter. The environment was drastically different: people were doing farming, fixing things, and kids were playing. For them, it was hard to believe. They were given good food and clothes. But Jona was still lost in his thoughts. He finished his meal and talked with Misa.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Misa, I'm going back for Mark.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> What? Jona, It's not safe out there. The shelter is the safest place for us right now.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> I know, Misa. But Mark risked his life to help us. I can't leave him out there alone.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> Wait, Jona. Maybe we can ask these people for help. They might give us a hand finding Mark.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> No Misa. I can't put others in danger anymore. I've seen many people died in my presence. But I won't make that happen again. I'm going alone. Do not feel bad If I don't come back, take care of yourself and the others for me.
          <br /><br />
          “A familiar face came and stood behind Jona.”
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Who is going where and why I'm not invited.
          <br /><br />
          “Jona turned around, and it was Mark with the smile on his face. Jona jumped on him and hugged him tightly."
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Jona, It's hard for me to breath. Your manly hugs are going to kill me one day for sure, and why are you crying?
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> It's nothing. Just happy to see you here.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> You know, Mark. He was about to leave to look out for you. He does care a lot about you. Like an older brother.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> Well, It was my mistake that I didn't make it in time to you guys. It took me a long to make a fool of those buglers, and it wasn't enough, I found some creatures along the way as well. But there weren't many. Most of the time I found only dead bodies of those creatures. I wonder who had killed them.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> I and my people group members take full responsibility for that.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> I don't believe you. It can't be.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> I know it's hard to believe, but it's the truth. We had to fight our way through to reach here, and we had casualties. But we managed to make it, and we found this shelter.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Misa:</span> Yes. It’s true, Mark. We were done with hiding. It was either us or them. So we fight for our lives, each one of us.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Mark:</span> That means my handcrafted weapons has fulfilled their purpose. Good to hear that.
          <br /><br />
          <span className={Styles.characterName}> ⫸ Jona:</span> Now we don't need to do that anymore. We can start new life here again. Building a new world for us and others.
          <br /><br />
          “Mark, Jona and Misa lived their life inside and outside the shelter. Dedicated their life in the service for others. They helped the farmers with their crops and taught them new techniques to improve their yields."
          <br /><br />
          "They worked tirelessly to make the shelter a better place for everyone, and gradually, more and more people started to join them. Together, they built a community where everyone worked for the common good, and there was no room for selfishness and greed.”











        </p>
      </div>
    </>
  )
}

export default SurvivingTogether