import Styles from '@/styles/TheVillage.module.css';
import Image from 'next/image';
import Village from "../../../public/Village.jpeg"
import Head from 'next/head'
const TheVillage = () => {
 return (
  <>
   <Head>
    <title>The Cursed Village</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
   </Head>

   <div className={Styles.name}>
    <h1>The Cursed Village</h1></div>

   <div className={Styles.p}>
    <h3>Estimated reading time: 19 mins 5 sec</h3>
    <div className={Styles.image}>
     <Image src={Village} alt="Village" width={900} height={500} priority />
    </div>
    <p>
     "Akira, a 25 year old solo traveler, who loved to escape from his normal life on weekends to experience new adventures. He loved being in nature, as it always made him feel at home. Despite not having a circle of friends, Akira formed a unique bond with nature that made him feel fulfilled, and he never felt the need to make any new friends, since his childhood."
     <p></p>

     "He grew up in a village with his grandparents, who were the only family he had. They would often take him to the jungle and mountains, sometimes to explore and sometimes to collect woods for fire. Even after his grandparent's death, Akira continued to cherish their memories and their shared love for nature."
     <br /> <br />

     "He carried his grandparents' picture with him whenever he was in nature to give him the comfort of feeling like they were with him.
     Despite getting old enough, he still followed the same tradition."
     <br /><br />
     "Just like any day, while researching his next destination, he found a village deep in the jungle far from any city and town. Akira had a unique approach to finding places to explore. He trusted only maps and never relied on websites or videos, which made his travels exciting and unpredictable, as he never knew what he would find."
     <br /><br />
     "Akira eagerly waited for the weekend and packed all necessary things in his bag pack. When the day came, he left for his destination, on bike. He was feeling that excitement, as he was getting closer to the jungle. When he arrived, he parked his bike at the border of the jungle and stepped inside the jungle for his new adventure.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> At last, I'm by the door of this jungle. Adventure, here I come.
     <br /><br />
     “Not far into the jungle, he stumbled upon a railway track, which seemed strange to him, as he had not seen any tracks leading into or out of the jungle in the map. Even his GPS device, that Akira was carrying, didn't show any rail tracks. Knowing it made him more excited about the place.
     He decided to follow the rail tracks.“
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> These tracks might lead me to some interesting places.
     <br /><br />
     “By the condition of those rail tracks, they were quite old. But they had become one with nature with plants all around them and the roof of tree branches above the tracks, making it look like it was the passage to the unknown world. Akira took out his grandparent's photo and showed it to the surroundings.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Look, Grandma and Grandpa, isn't it a great place? I wish you guys were here to see this.
     <br /><br />
     “Akira took out his phone and clicked a good pic of this scenery, then continued his walk. After following the rail tracks for miles, he came across a river with a wooden platform built on it.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> This is quite strange, a platform above the river. Perhaps it's for water supply to the nearby village. The people living in such a remote environment seem quite resourceful.
     <br /><br />
     “When Akira looked carefully, he saw two men on the other side of the river. He decided to cross the river to get to the other side.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Hello, it is nice to meet you. I'm just here to explore this place and village. Can either of you tell me about this place and the rail track's history?
     <br /><br />
     “Those two gave Akira a dead look for a few seconds, then ignored him as if he wasn't even there. The situation made Akira uncomfortable, so he decided to leave them and head back to the rail tracks.”
     <br /><br />

     <span className={Styles.characterName}> ⫸ Akira:</span> Well, that was awkward. Did I offend them? Or they just they don't speak my language? Maybe I'll find someone else who can tell me about this place.
     <br /><br />

     “He shook his head and continued on his way. As Akira moved forward, he kept looking at his GPS to verify where the rail tracks were leading him.”
     <br /><br />

     <span className={Styles.characterName}> ⫸ Akira:</span> Is that a cave? I must say, this trip has just started yet, and I'm coming across so many things already. I couldn't ask for more. For now, let's ignore the cave. It must be dark inside, and going inside the cave alone is quite dangerous.
     <br /><br />
     “As Akira turned his back on the cave, he noticed a kid standing in front of him. Startled by the sudden appearance, Akira screamed out loud.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Oh god, You scared me, little guy. Where did you come from?
     <br /><br />
     ⫸ Kid: Why are you here?
     <br /><br />
     “The kid spoke to Akira in a serious tone, his eyes fixed on him as if he had done something wrong.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> What do you mean kid? I'm here for fun. Do you know what's inside the cave?
     <br /><br />
     ⫸ Kid: You shouldn't be here. We are not allowed to talk about the cave.
     <br /><br />
     “The kid ran after he finished talking with Akira.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Hey kid, wait!, That was one strange kid. Seems he didn't like it, me being here. However, now I know that they can understand my language and that's a good sign. Keep going, Akira, our final destination is the village.
     <br /><br />
     “Akira finally arrived in the village and found everything to be normal. People were going about their daily activities, shops were open, and farmers were transporting their crops. As he walked through the village.
     Akira anticipated it was going to be the train, but it was rather a long handcar with the capacity of carrying 40 to 50 people, which had proper seats as well.”
     <br /><br />
     "Akira again took some pictures with his phone. He even noticed that there was no network on his phone, which was obvious since he was in the middle of the jungle. After walking for so long, Akira felt hungry, which led him to a small shop. There he bought some cookies and chips. He didn't waste any time and just opened the packet, started eating at the shop, and watched all the activities. It reminded him of his past when he used to live in a village."
     <br /><br />
     "After finishing his meal, Akira continued on his way and turned a corner where he saw a group of people. They didn't look like they were from the village, so he approached them to find out more. Surprisingly, the group was actually filming a documentary about the village. It was the first time he had seen a documentary being filmed. The interviewer was asking questions, and the old people were answering them.”
     <br /><br />
     “Suddenly, Akira saw someone running towards the film crew holding an axe. He felt scared when he saw what was happening. The person with the axe attacked one of the crew members twice in the face without any hesitation. Everyone was terrified and ran for their lives. The man's behavior and appearance made it evident that he was not a human being. The left side of his face was completely gone, leaving only raw flesh and blood dripping down.”
     <br /><br />
     "Akira also ran for his life and hid inside a house, peaking through a small gap in the door. There was no one outside but him. He couldn't believe that just a while ago the place had been full of people, and now there was only the dead body and the crazed man. That man was breathing fast. He went closer to the dead body and hit it with the axe again. He didn't stop until the head of the dead body was gone. The man looked around, screamed loudly, and ran away.”
     <br /><br />
     "Inside the house, Akira went into shock. He wasn't ready to believe that it was all real. When he saw movement behind the pile of clothes, he got scared and screamed out of fear. A man came out from behind the pile of clothes, put his hand on Akira's mouth, and gestured for him to stay quiet.
     Akira nodded, and the man removed his hand. In a low tone, Akira asked the man.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> What was that? Who is that man? How is he even alive with one side of his head is missing?
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> He told you people not to investigate further, didn't he? This is what you get for not listening to him. Now that he's back, It'll be even harder for you to escape this place.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Hey, wait, Who’s he? I have no idea what you are talking about? And I'm not investigating anything.
     <br /><br />
     ⫸ Mao: You are the part of that filming crew, aren't you?
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> No, I'm not. I'm just here to explore this village. I had no idea what was happening here.
     <br /><br />
     ⫸ Mao: Mister, you made a terrible mistake by coming here in this kind of situation.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> What do you mean by a terrible mistake? Could you please clear things out? You are talking all in a maze.
     <br /><br />
     ⫸ Mao: Listen carefully, Mister. The person you just saw outside was already dead. He died two days ago in a terrible accident in the jungle. We were setting up traps to catch animals. Accidentally, his leg slipped, and he fell onto the trap, causing his left side head to be cut off instantly, leading to his death.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Then, How did he come back to life, all of a sudden?
     <br /><br />
     ⫸ Mao: It was the doing of Mukcha. He lived inside the cave. It was an old dark spirit. Those people you saw back there who were filming everything, they wanted to unveil the mystery behind the cave. That spirit had already warned them in various ways. But they just decided to ignore it. The guy he just killed must have done something terrible to make him this angry.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Then I made a mistake by coming here. Now I understand why that kid, by the cave, told me that I shouldn’t be here.
     <br /><br />
     ⫸ Mao: Did you go inside the cave? All villagers are prohibited from going there. Any person from the village ends up dead when they get inside the cave. Maybe the kid you saw was the spirit. No one knows what's really inside that cave. Whoever dies there, their spirit wanders in the jungle. It's a curse on the villagers.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Then don't you think we should help those film crew members?
     <br /><br />
     ⫸ Mao: Are you out of your mind? Did you forget what I just said?
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> I understand what you said. After hearing it all I'm definitely  scared but still we need to find those people, and escape from here. No one needs to die here for nothing.
     <br /><br />
     ⫸ Mao: Could you tell me about the kid you saw by the cave?  What did he look like?
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> He was around 4 or 5 years old, I guess. Short hair, blue t-shirt and white shorts. Why did you ask?
     <br /><br />
     "Mao broke down in tears and started hitting the floor in frustration. Akira quickly intervened and prevented him from injuring himself further."
     <br /><br />
     ⫸ Kaira: Are you okay? Stop punching the ground. You will hurt yourself.
     <br /><br />
     ⫸ Mao: He was my son. Five years ago, he got lost in the jungle. We searched everywhere for him, but we couldn't find him. The next day, the farmers found his dead body in front of the cave.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> I'm sorry to hear that. I remember your son's face. It was lifeless. Isn't there any way to free the spirits of the dead and lift the curse? There may be someone in the village who knows about the real story behind the curse.
     <br /><br />
     ⫸ Mao: There is one man, who might know about this.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Let's find him then, But we need to save those film crew as well.
     <br /><br />
     ⫸ Mao: Leave that to me. Once we find out more about the cave curse, I'll find and gather the film crew at one place. But first, we need to go to the old man's place. He's a local expert on the area and may be able to shed some light on the curse.
     <br /><br />
     “Having carefully inspected their surroundings, Akira and Mao left the house and made their way to the old man's place. They moved cautiously, carefully avoiding the attention of the undead creature that lurked nearby. But they were unaware that the creature had climbed onto the roof of the house and watched their every move, waited for the right moment to strike."
     <br /><br />
     "He jumped from the house and hit his face hard on the ground. There was no movement for a moment, and Akira thought he was dead. But then he suddenly began to move in an abrupt, jerky way. Mao pulled Akira back, and they started to run for their lives once again. After a lot of effort, they finally managed to find their way to the old man's house and went inside.”
     <br /><br />
     “Old man was already going through some of his books. Mao introduced the old man to Akira, and then Akira told him everything about the incident by the cave and the dead guy.”
     <br /><br />
     ⫸ Olwek: Are you certain you saw Mao's son's spirit?
     <br /> <br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Yes, I'm pretty sure there was a kid, even before the kid I met two guys by the river platform.  But They didn't talk with me.
     <br /><br />
     “Olwek took out the picture of the album and showed it to Akira.”
     <br /><br />
     ⫸ Olwek: Are these two were there?
     <br /><br />
     “Olwek pointed his finger to one picture.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Yes, It’s them. Were they spirits too?
     <br /><br />
     ⫸ Olwek: I'm afraid so. They died 20 years ago because of that cave. They were non-believers of Mukcha and went inside the cave to prove to the villagers that it was just a fairy tale, they went inside the cave and never returned. But there was one interesting thing I noticed recently about the cave. When the film crew went inside, nothing happened to them. We even asked what they saw inside, but they decided to share that after finishing their documentary.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Olwek, do you know the history of Mukcha and the cave?
     <br /><br />
     ⫸ Olwek: Yes, I have heard stories from my grandparents. Around 300 years ago, there was a man named Mukcha who lived in a village with his wife and two daughters. He was considered the wealthiest person in the village, but the villagers believed that he was practicing black magic. They often saw him entering a nearby cave with different animals, which confirmed their suspicions.
     <br /><br />
     Eventually, the news about Mukcha's black magic practices spread throughout the village, and a group of angry villagers gathered outside his house. Fearing for his safety and the safety of his daughters, Mukcha escaped through a window with his two daughters, leaving his wife behind. Unfortunately, the villagers captured his wife and beat her to death. The next day, they hung her body from a tree and set it on fire.
     <br /><br />
     Mukcha saw everything happening. He waited for everyone to leave, so he could collect his wife's leftovers. But he was unaware that the villagers were hiding in the bushes, waiting for him to appear. When he stepped out into the open, they attacked him, but he somehow managed to escape again. He ran back to the cave, and the villagers followed him. To Mukcha, the cave was like a stronghold of protection.
     <br /><br />
     As the villagers entered the cave, Mukcha chanted some mantra and slit the throats of his two daughters, splashing their blood all over the villagers. This horrific act left everyone scared and shocked.
     <br /><br />
     ⫸ Mukcha said: You people killed my wife. Without knowing the whole truth. Now you must see the wrath of the dark power upon this village. I cursed you all villagers. You will never be able to leave this village nor this jungle. Those who will try to leave are going to die a miserable death. And those who will set foot in this cave are going to die, and their spirit will be stuck here in this place forever.
     <br /><br />
     After finishing his words, Mukcha stabbed himself in the neck. Those who were in the cave started running to get out, but some stayed and ended up dying. Since then, we have been stuck here in this village, bound by the curse.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> I believe, there is something important in the cave, that's why villagers are not allowed to get inside. We need to find out about it, It can lead to break the curse on villagers.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Then we must see the cave. I can go inside to find out the truth.
     <br /><br />
     ⫸ Mao: With him out there, we may find it hard to get to the handcar. We can use yourself as a bait to lure that dead man.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> You have a plan in your mind?
     <br /><br />
     ⫸ Mao: Yes, you have to be in an open spot to get his attention, and I will tie some fishing lines on the pole from each side around you. As we know, he is too aggressive, he will run to you, without a second thought, getting caught in our trap. I hope it will cut his flesh enough to slow him down. Then we can attack him, once he hits the ground.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Not the best idea, but, we can try it.
     <br /><br />
     "Mao and Akira set up the trap and waited for the dead man, making sounds to get his attention. When he eventually arrived with his axe, he was even bloodier than before. As Mao predicted, he ran towards Akira and the fishing line cut into his already disfigured mouth. The more force he applied, the deeper the cut became.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Mao, I think the fishing line is stuck in his jaws. Hurry, attack his head.
     <br /><br />
     “Akira hit the dead man's arm that held the axe. Mao was unsure, but he eventually cut off the dead man's head. The villagers watched from inside their houses and came out when the dead man fall to the ground.”
     <br /><br />
     ⫸ Villager 1: Don't think it's going to be an end. He will come back in other from again. Now you two have become his prime target. As long as you two are in this territory, he will hunt you down. Traveler, you must leave this place while you have chance.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> No, I can't leave until I find the other crew members. Does anyone of you know their whereabouts?
     <br /><br />
     ⫸ Villager 2: In total, they were 10 people when they came in the village. Dead man already killed 4 of them brutally. I saw the remaining six of them escape to the mountains.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Mao, do you think we will be able to find them in those mountains.
     <br /><br />
     ⫸ Mao: It will be a tough job, but not impossible. However, I suggest we shouldn't pursue them. The root cause of this curse is in a cave, and you're the only one who can go inside the cave and uncover what's really inside, it might help those film crew members survive.
     <br /><br />
     "The other villagers chose not to support Mao and Akira because they were afraid that Mukcha might come after them too. Hence, the two of them got onto a handcar and headed towards the cave."
     <br /><br />
     ⫸ Mao: You have to be vigilant when you will be in that cave. Take this lamp and axe with you; I will stay outside waiting for you.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> I need you to make a promise to me. If I don't come out by evening, you must go into the mountains to find the rest of the crew members.
     <br /><br />
     ⫸ Mao: I don't need to make a promise for that, You will come out of this cave safe, and we will find them together.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Thanks for the motivation. I've always been scared of going into a cave, and now I'm going into one, such an irony. Time for me to face my fear.
     <br /><br />
     “With all his courage, Akira entered the cave. He noticed many cave drawings.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> This cave drawing definitely connects with Mukcha and the village. It shows a group of people and a man sacrificing two kids. It's like someone has portrayed the incident that happened 300 years ago, as Olwek has told me.
     <br /><br />
     “As he walked further into the cave, Akira came across various cave drawings and symbols on the walls. Some of which seemed to depict black magic rituals and incantations. He observed each one carefully, trying to understand their meaning. But then he heard footsteps running towards him. He turned back, but no one was there. With the help of the lamp, he continued walking deeper into the cave. Akira's heart pounded with each step. Suddenly, he heard girls giggling in the distance. Despite feeling uneasy, he kept going. Eventually, he reached a dead end in the cave."
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> It's not possible that there's nothing here. Where are the dead bodies of Mukcha and his daughters? Think Akira, think. Maybe they're underground. The only way to find out is by digging.
     <br /><br />
     "Akira began digging with his axe. The light from his lamp was fading, so he had to work quickly. He dug with all his strength until he felt the axe hit something solid. After carefully removing the soil, he found a skull. Continuing to dig, he discovered the bodies of Mukcha's daughters lying next to each other."
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> How is this possible, it’s been 300 years since Mukcha killed his daughters, yet their body just as fresh as they have died some minutes ago. Perhaps these bodies are keeping the curse alive. If I take out these bodies out of the cave to Olwek, He might be able to find the mystery behind it.
     <br /><br />
     "Akira picked up the bodies and suddenly the cave went dark. He couldn't find his lamp and had to navigate through the cave walls carefully with his hands to find his way, while carrying the bodies. Then, he felt movement in the dead body and got scared. He threw the bodies and started to run, but something grabbed his leg and he fell down. The hands moved up to his neck, Akira's body became paralyzed with fear. He couldn't move a muscle as the grip around his neck tightened. He was being choked by the hands.”
     <br /><br />
     "Akira's life flashed before his eyes as he struggled to breathe. He thought this was the end, but suddenly a bright light flashed and illuminated the entire cave. Caused lifeless bodies became motionless once again. Confused by the sudden burst of light, Akira got up and carried the bodies again. When he finally made it out of the cave and looked back, he saw his grandparents smiling at him."
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Grandpa, grandma, thank you so much for saving me!
     <br /><br />
     "With those words, Akira ran back towards the cave, but as he arrived, he found that his grandparents had disappeared."
     <br /><br />
     ⫸ Mao:  Akira, what happened?
     <br /><br />
     “Akira took out a picture of his grandparents from his pocket and smiled.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Nothing, just my grandparents. Anyway, these are the dead bodies of Mukcha’s daughters. I think they have something to do with the curse.
     <br /><br />
     “They saw Olwek heading their way.”
     <br /><br />
     ⫸ Mao: Why did you risk your life by coming here?
     <br /><br />
     ⫸ Olwek: I found something important while I was going through my ancestral old archives. And there I found the mention of the cave. It goes back to thousands of years old. This cave used to be the holy place for dark magic, where one could achieve anything by sacrificing a life. Somehow, Mukcha was able to decode the cave drawings and gained wealth by sacrificing animals.
     <br /><br />
     Even in his last moment, he was so blinded by greed to achieve anything by the dark magic that, in order to make his wish true to become immortal, he sacrificed his own daughters, and to make his daughters immortal as well, he sacrificed himself. I suppose you have found something else in the cave.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> These are the dead bodies I found that were out of the ordinary. That's why I took them out.
     <br /><br />
     ⫸ Olwek: It is so strange. After all these years, they are still in the same form.
     <br /><br />
     ⫸ Akira: But I don't get it, They all were being sacrificed to become immortal. Yet they were dead. There were only bones of Mukcha’s body, and His daughters bodies were fine. Could you explain that?
     <br /><br />

     ⫸ Olwek: They did become immortal but in the spirit form, not in human form. And about His daughters' body conditions, it may be because they were children with pure souls that's why they maintained the same form, while Mukcha's spirit was already corrupt by his greed, and that's the reason his body decayed over time.
     <br /><br />
     “As Olwek touched one of the body of Mukcha’s daughter, It began to decay, eventually tuned into dust. And a loud scream came out of the cave.”
     <br /><br />
     ⫸ Olwek: I get it now, Mukcha bound this curse to the bodies. As long as their bodies remain intact, the curse will remain in effect. It will free all the spirits from this place, including your sons as well, Mao.
     <br /><br />
     “Olwek moved forward his hand to touch the other body, but out of nowhere, an axe appeared and cut his arm into two pieces. He began to scream out loud in pain.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Mao, look there at tracks, one of the film crew members.
     <br /><br />
     ⫸ Mao: We need to carry Olwek and take him to the handcar. That man is possessed by Mukcha. Hurry up, or we will all be in danger.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Mao, just touch his daughter's body and see if it can break the curse.
     <br /><br />
     “Mao touched the body of Mukcha's daughter, and it turned to dust. Again they heard a loud scream coming from the cave. Mao and Akira quickly took Olwek and left the area on a train. Mukcha stayed behind and watched as they left.”
     <br /><br />

     “Akira wrapped up Olwek’s arm with a piece of cloth.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> What are we going to do now? He has lost lots of blood. Olwek don't close the eyes, stay with me.
     <br /><br />
     ⫸ Mao: I'm thinking, I’m thinking. You said in the cave there are Mukcha's bones, right? If you can somehow retrieve his skeleton, I can destroy it.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Mao, now I don't think he will leave the cave open for me to get in. That's why he didn't follow us.
     <br /><br />
     ⫸ Mao: This time, I will convince all the villagers to help us, no matter what. This curse is on the verge of breaking. This time it has to be done. Is Olwek holding up well?
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> He is already dead. Mao.
     <br /><br />
     “Mao punched the handle in anger. They remained silent until they reached the village. Mao gathered all the villagers and told them everything about how Mukcha’s daughter turned into dust as Olwek made contact with the dead body.”
     <br /><br />
     ⫸ Mao: If we fight together just this once to end this curse, our future generations won't have to spend their whole lives in this place. The spirits wandering in the jungle will be free as well. It's a situation of now or never. We can't let Olwek's death be in vain. So I ask you all, will I get your support just this once?
     <br /><br />
     “Some villagers took a step forward and agreed to help him, some stayed behind. They all were well prepared. After Olwek burial ceremony, they got on a handcar and approached to the cave.”
     <br /><br />
     ⫸ Mao: Everybody listen, we must protect Akira from Mukcha at all cost. Some of us will create a diversion, so Akira can get inside the cave to take out Mukcha’s skeleton. He might use his dark magic, so keep a safe distance from him.
     <br /><br />
     “From the distance, Mao noticed All the film crew members guarding the cave. They all were dead and controlled by Mukcha.”
     <br /><br />
     ⫸ Villager 1: You said he would be alone, but here the picture is different.
     <br /><br />
     ⫸ Mao: He must have killed all those film crew members who ran in the mountains.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Everyone, I'm scared, and I know you all might be too. But this is a live or die situation. Either we defeat Mukcha and end this curse, or he will destroy us all. I ask you to create a distraction and make a small opening for me to get inside the cave. That's all I ask of you, and I promise I'll do everything in my power to take out Mukcha’s bone out from the cave.
     <br /><br />
     ⫸ Mao: Did you all hear what he just said? Now let's get down there and end this once and for all.
     <br /><br />
     “Akira's words gave them all a little courage to fight. Akira stayed behind, and the rest of the villagers jumped into the fight. Possessed film crew members were fighting like savages, and it was clear to see how angry Mukcha was about his daughters. They were all giving a tough fight.”
     <br /><br />
     “Meanwhile, Akira’s eyes went to the kerosene cans. He told everyone to move on his signal.”
     <br /><br />
     ⫸ Akira: I never thought, I would do such a thing, forgive me grandpa and grandma. Everyone, get back right now, it's kerosene I'm throwing right at you.
     <br /><br />
     "He took out his emergency survival lighter and threw it at the film crew members. In an instant, the place caught fire, so did the film crew members. Despite being on fire, they kept fighting until their bodies gave up, and they fell down one by one."
     <br /><br />
     ⫸ Mao: Akira, it's your chance. Get inside quickly.
     <br /><br />
     “Akira ran inside the cave. He was shocked to see that the cave drawings caught fire and were disappearing. It was not enough that the whole cave started to shake, which was a sign for Akira to hurry. He got to Mukcha’s bones, packed it in a piece of cloth, and ran back. When he saw the opening of the cave crumbling and about to close, he closed his eyes and pictured his grandparents.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> I'm not going to die here. I will get out of this place.
     <br /><br />
     “With these words, he jumped and made his way out of the cave through a small opening. Everyone was surprised to see him emerge successfully.”
     <br /><br />
     ⫸ Mao: We really thought you would be dead and wouldn't make it out alive.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> I won't die that easy, my grandparents won't let me.
     <br /><br />
     ⫸ Mao: Come again?
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Nothing, Here are the bones of Muksha. Free everyone from this curse.
     <br /><br />
     "Mao touched Mukcha’s bones, and they turned into ashes. He then heard someone calling 'father,' as he turned around, it was his son smiling at him."
     <br /><br />
     ⫸ Mao: Son, come here. Where were you all this time?
     <br /><br />
     ⫸ Kid: I was playing in the jungle, father, and I'm here to say goodbye because now I'm leaving this place. I will stay with mother now, father, so don't miss me and cry alone at nights.
     <br /><br />
     “Mao controlled his emotion.”
     <br /><br />
     ⫸ Mao: I won't, son. But don't make trouble for your mother, promise me.
     <br /><br />
     ⫸ Kid: I will never. Father, I'm leaving now.
     <br /><br />
     “Mao couldn't hold back his emotions any longer and burst into tears, knowing it would be the last time he would ever see him. Akira tapped his shoulder to comfort him.”
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> He's finally free now.
     <br /><br />
     ⫸ Mao: Yes he is, What are you going to do now Akira?
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Because of this Mukcha, I haven't been able to explore the whole village yet. Would you become my guide to show me around?
     <br /><br />
     ⫸ Mao: Anything for you, Akira. You owe us big time.
     <br /><br />
     <span className={Styles.characterName}> ⫸ Akira:</span> Mao, I will always remember this adventure I’ve had here.
     <br /><br />
     “After the curse of Mukcha was lifted, and the cave was sealed, the villagers were finally able to travel outside the jungle without fear. The jungle became a popular tourist attraction and Mukcha's story became a legend. Though he was gone, his memory lived on among villagers.”

    </p>
   </div>
  </>
 )
}

export default TheVillage