import Styles from '@/styles/TheVillage.module.css';
import Image from 'next/image';
import Trap from "../../../public/trap.jpg"
import Head from 'next/head'
const TrapHouse = () => {
     return (
          <>
               <Head>
                    <title>Trap House</title>
                    <meta name="description" content="Generated by create next app" />
                    <meta name="viewport" content="width=device-width, initial-scale=1" />
                    <link rel="icon" href="/favicon.ico" />
               </Head>
               <div className={Styles.name}>
                    <h1>Trap House</h1></div>

               <div className={Styles.p}>
                    <h3>Estimated reading time: 3 mins 37 sec</h3>
                    <div className={Styles.image}>
                         <Image src={Trap} alt="Traphouse" width={900} height={500} priority />
                    </div>
                    <p>
                         After a long day at work, Haru hopped on his bike and started riding home. However, out of tiredness, he decided to take a break and pull over to the side of the road. The place where he stopped was peaceful, crowded with trees and lacking any signs of human activity. Just a few steps away, an old, abandoned house caught his eye. It was the only house he could see in the area, and it looked quite old. So, he parked his bike to take a break. Exhausted, Haru decided to rest on the steps of the house for a while to recharge before continuing his journey home.
                         <br /><br />
                         When Haru, cleaned the steps to sat down. He felt like someone was watching him, and the air around him grew colder. Suddenly, he saw a girl hanging in midair on the road. Her eyes were black, with a twisted face, carrying a terrifying smile. The girl then fell to the ground and disappeared. Haru realized that it was not human. The moment that girl fell on the ground, Haru heard a soft whisper in his ear, when he turned to look, the atmosphere had changed dramatically. Thick, black smoke was pouring out of the doorway with a rotten smell.
                         <br /><br />
                         Haru immediately ran back to the road, and just then, three sisters arrived on the scene. Unaware of Haru’s situation, the eldest sister noticed Haru’s bag on the steps of the house and ran to retrieve it. Haru tried to stop her, and told the sisters everything he had witnessed a while ago. One of the sisters said, they often play in this house courtyard, and they have never seen anything. Nevertheless, as the eldest sister reached the steps, a dark figure emerged from the front door and dragged her into the house. Slamming the door shut.
                         <br /><br />
                         The other sisters and Haru were left shocked and helpless. Not knowing what to do. The eldest sister suddenly fell from the sky in front of them, completely unconscious. Despite the impact of the fall, she had no visible injuries. They were all relieved to have her back, but the experience left them shaken.
                         <br /><br />
                         Haru tried to call for help, but there was no network in his phone. Haru got on his bike, but even the bike couldn't start. Unfortunately, he had to carry the eldest sister and run for their lives. After running for a while, they came across the other house and knocked on the door for help. An old woman answered and agreed to let them use her old telephone.
                         <br /><br />
                         Haru laid down the eldest sister on the sofa and dialed the number. But as he spoke, he heard strange white noise and chattering on the other end. Suddenly, a voice said, “Welcome to my house. You won't be leaving now.” Haru felt shivering all over his body and looked around, but the old lady was nowhere to be found.
                         <br /><br />
                         Without wasting any time, Haru carried the eldest sister in his arms and ran to the door. As he opened it, the other sisters were able to leave the house safely, but a dark figure held back Haru’s leg, trying to stop him from leaving. He tried, but couldn't free his leg from it. He chose to throw the eldest sister outside the house and yell out loud for the sisters to run away as far as they could. The door then slammed shut behind them with a growling voice came from inside the house, echoed in the surrounding area.
                         <br /><br />
                         The sisters carried their eldest sister back home safely, and her parents hospitalized her. Traumatized by the experience, they eventually opened up about what they had gone through. The police then investigated the area where Haru was last seen, but there was no trace of the house nor Haru’s whereabouts. The search for Haru continued for weeks, search parties scoured the surrounding forests and towns, but they found no sign of him.
                         <br /><br />
                         After several days spent in the hospital unconscious, the eldest sister regained her consciousness, but there was something strange about her. She acted like an animal, growling and attacking people. The doctor said it might be because of the hit she took on her head when she fell on the ground. They gave her many sedatives, but it made her situation worse. Eventually, the doctors diagnosed her with multiple personality disorder.
                         Days went by, and her appearance had changed so drastically that her own sisters hardly recognized her.
                         <br /><br />
                         As time passed, the incident became a topic of interest in the local news and media, and people started speculating about what could have happened to Haru. Some thought he may have been swallowed up by a mysterious portal. The story even caught the attention of paranormal investigators, who were called in to help explain the unexplainable. Despite their efforts, the truth behind Haru's disappearance remains a mystery, leaving many to wonder if there truly is a supernatural explanation for what happened.
                         <br /><br />
                         On the other end, the eldest sister mysteriously disappeared from the hospital. Even search parties failed to find her, just after Haru, the eldest sister became hot topic for the media for a while, then everyone forgets about her as well.
                         <br /><br />
                         When the eldest sister went missing from the hospital, she somehow appeared on the same spot where everything had started. She was in the middle of the road, floating and Haru saw her, while cleaning the steps. That mysterious floating girl was none other than the eldest sister who traveled back in time. The unknown energy from that house caused it.
                         <br /><br />
                         This never ending loop kept happening, with the eldest sister appearing out of nowhere and then disappearing, her past self being dragged into the house, and then falling to the ground from the sky. Haru confronts the unknown energy in the other house. The same events repeated themselves, over and over again, trapped in a supernatural time loop.

                    </p>
               </div>
          </>
     )
}

export default TrapHouse